name: clang-format-lint

on:
  pull_request:
    branches: [ develop, main ]

jobs:
  formatting-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: DoozyX/clang-format-lint-action@v0.11
      with:
        source: '.'
        extensions: 'h,hpp,cpp,cu,cuh'
        clangFormatVersion: 11
